# Generated by Django 5.2.6 on 2025-09-21 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_submit_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Tide'), (2, 'Coastal Damage'), (3, 'Flooding'), (4, 'Waves'), (5, 'Swell'), (6, 'Surge'), (7, 'Storm'), (8, 'Tsunami')], verbose_name='Hazard inputted by the user')),
                ('user_text', models.CharField()),
                ('user_video', models.FileField(upload_to='report_videos/')),
                ('user_ip', models.GenericIPAddressField(verbose_name='IP used to make the report')),
                ('user_userAgent', models.CharField(verbose_name='UserAgent of the browser')),
                ('user_platform', models.CharField(verbose_name='Platform of the user')),
                ('user_device_language', models.CharField(verbose_name="Device language of the user's device")),
                ('action_status', models.IntegerField(choices=[(0, 'To Be Started'), (1, 'In Progress'), (2, 'Next Stage'), (3, 'Finish')], default=0, verbose_name='Status of the action')),
                ('geovideo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.geovideo')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
