# Generated by Django 5.2.6 on 2025-09-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='user_video',
        ),
    ]
