# Generated by Django 5.2.6 on 2025-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0002_remove_userreport_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='coins',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Coins given till now'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='verification',
            field=models.IntegerField(choices=[(-2, 'Discarded'), (-1, 'Not Severe'), (0, 'Not System Processed'), (1, 'Not Acknowledged'), (2, 'In Progress'), (3, 'Personnel Unconfirmed'), (4, 'Verified')], default=0, verbose_name='Status of the verification'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='user_submit_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Tide'), (2, 'Coastal Damage'), (3, 'Flooding'), (4, 'Waves'), (5, 'Swell'), (6, 'Surge'), (7, 'Storm'), (8, 'Tsunami'), (9, 'Other')], verbose_name='Hazard inputted by the user'),
        ),
    ]
