# Generated by Django 5.2.6 on 2025-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0003_userreport_coins_userreport_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='proccessed_data',
            field=models.JSONField(default=None, null=True, verbose_name='Output from the AI models'),
        ),
    ]
