# Generated by Django 5.2.6 on 2025-09-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0004_userreport_proccessed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='confidence',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Confidence between 1-100 on the system based on the AI model system'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='severity',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Severity between 1-100 based on the AI model system'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Tide'), (2, 'Coastal Damage'), (3, 'Flooding'), (4, 'Waves'), (5, 'Swell'), (6, 'Surge'), (7, 'Storm'), (8, 'Tsunami'), (9, 'Other')], default=None, null=True, verbose_name='Type of the hazard determined by the system using the input & AI model system'),
        ),
    ]
