# Generated by Django 5.2.6 on 2025-09-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0005_userreport_confidence_userreport_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='language',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
