# Generated by Django 5.2.6 on 2025-09-21 13:59

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.CharField(blank=True, max_length=255)),
                ('software_info', models.CharField(blank=True, max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('direction', models.FloatField(blank=True, null=True)),
                ('gps_fix_type', models.CharField(blank=True, max_length=50)),
                ('num_satellites', models.IntegerField(blank=True, null=True)),
                ('timestamp_utc', models.DateTimeField()),
                ('orientation_roll', models.FloatField(blank=True, null=True)),
                ('orientation_pitch', models.FloatField(blank=True, null=True)),
                ('orientation_yaw', models.FloatField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('aperture', models.FloatField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('lens', models.CharField(blank=True, max_length=100)),
                ('accelerometer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, size=None)),
                ('gyroscope', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, size=None)),
                ('magnetometer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, size=None)),
                ('barometer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), blank=True, default=list, size=None)),
                ('orientation_series', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, size=None)),
                ('raw_sensor_path', models.CharField(blank=True, help_text='Path to .npz or .json.gz file', max_length=1024)),
                ('accel_min', models.FloatField(blank=True, null=True)),
                ('accel_max', models.FloatField(blank=True, null=True)),
                ('accel_mean', models.FloatField(blank=True, null=True)),
                ('gyro_min', models.FloatField(blank=True, null=True)),
                ('gyro_max', models.FloatField(blank=True, null=True)),
                ('gyro_mean', models.FloatField(blank=True, null=True)),
                ('mag_min', models.FloatField(blank=True, null=True)),
                ('mag_max', models.FloatField(blank=True, null=True)),
                ('mag_mean', models.FloatField(blank=True, null=True)),
                ('baro_min', models.FloatField(blank=True, null=True)),
                ('baro_max', models.FloatField(blank=True, null=True)),
                ('baro_mean', models.FloatField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='report_videos/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp_utc'], name='geovideo_ts_idx'), models.Index(fields=['recorded_at'], name='geovideo_recorded_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='geovideo_location_gix')],
            },
        ),
    ]
