# Generated by Django 5.2.6 on 2025-09-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geovideo',
            name='raw_sensor_path',
        ),
    ]
