# Generated by Django 5.2.6 on 2025-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_geovideo_raw_sensor_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geovideo',
            name='gps_fix_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='geovideo',
            name='lens',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='geovideo',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
