# Generated by Django 5.2.6 on 2025-09-21 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_geovideo_gps_fix_type_alter_geovideo_lens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geovideo',
            name='accelerometer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='geovideo',
            name='barometer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='geovideo',
            name='gyroscope',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='geovideo',
            name='magnetometer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='geovideo',
            name='orientation_series',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4), blank=True, default=list, null=True, size=None),
        ),
    ]
